---
title:  "OpenEMR Table Definition Inspector"
runtime: shiny
output:
  html_document:
    highlight: espresso
    code_folding: hide
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**View any CREATE TABLE statement in openemr/master/sql/database.sql**

*Notice the Code button*

[Fork me on Github](https://github.com/johnbwilliams/openemr_table_definition_inspector)

```{r}
suppressMessages(library(tidyverse))
suppressMessages(library(data.table))
library(stringr)
library(shiny)
# --------------------------------------------------
# Read database.sql
url <- "https://raw.githubusercontent.com/openemr/openemr/master/sql/database.sql"
dfy <- as.tibble(fread(url, sep = "\n", blank.lines.skip = TRUE))
names(dfy)[1] <- "val"
# ---------------------------------------------------------------------
#  enclose with back ticks all (twelve) unenclosed table names:
#    chart_tracker, ar_session, ar_activity, gprelations, code_types, version, 
#    ccda_components, ccda_sections, ccda_field_mapping, ccda,  ccda_table_mapping,  
#    calendar_external
is_ticked <- function(s) {
 grepl("^.+\`.+$", s)
}
tick_it <- function(s) {
  new <- str_replace(s, "LE ", "LE `")
  str_replace(new, " \\(", "` \\(")
}
dfx <- dfy %>%
  mutate(val = ifelse(is_ticked(val), val, tick_it(val))); rm(dfy)
# ------------------------------------------------
# create list of all OpenEMR SQL table names, for UI Drop down menu
table_names_df <- dfx %>% 
  filter(grepl("^CREATE.+", val)) %>%
  mutate(oemr_table_names = str_extract(val, regex("(?<=\`).*(?=\`)")))
# --------------------------------------------------
# Function to extract Create Table SQL statement from database.sql
# Called from UI upon table name selection from drop down menu
get_Create_Table_statement <- function(table_name) {
  pattern <- paste("`", table_name, "`", sep = "")
  len <- nrow(dfx)
  i <- 0
  # Find first row # of CREATE TABLE statement
  done <- FALSE
  while ((i <= len) & !done) {
    i <- i + 1 
    s <- as.character(dfx[i, 1])
    if (grepl(pattern, s) & grepl( "^CREATE.+", s)) done <- TRUE
  }
  begin <- i
  # Find last row # of CREATE TABLE statement
  done <- FALSE
  while ((i <= len) & !done) {
    i <- i + 1 
    s <- as.character(dfx[i, 1])
    if (grepl("ENGINE", s)) done <- TRUE
  }
  end <- i
  return(dfx[begin:end, 1] %>% rename(" " = val))
}
# -----------------------------------------------------------
# Display UI - dropdown menu for selection of table name 
#            - display selected CREATE TABLE SQL statemenmt
shinyApp(
  ui = fluidPage(
    wellPanel(selectInput("selected_table", 
                          "Select Table Name:", 
                           table_names_df$oemr_table_names, 
                           selectize = TRUE
             )
    ),
    wellPanel(tableOutput("create_table_statement"))
  ),
  server = function(input, output) {
    output$create_table_statement <- renderTable({get_Create_Table_statement(input$selected_table)
    })
  },
  options = list(height = 500)
)
```

